In [15]:
import tensorflow_hub as hub
import tensorflow.compat.v1 as tf
#Import all the dependencies
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
import numpy as np
import re
from sklearn.feature_extraction.text import CountVectorizer
# import the metrics class
from sklearn import metrics
import matplotlib.pyplot as plt
import warnings
from nltk.tokenize import word_tokenize

In [2]:
warnings.filterwarnings('ignore')
#warnings.filterwarnings(action='once')

In [3]:
#read in the preprocessed data as csv using pandas
df = pd.read_csv("preprocessed_data.csv")
df.head() #take a look

filepath   age  gender  mmse  pause1  pause2  pause3  \
0  138-1.cha  68.0  female  28.0       0       0       1   
1  631-0.cha  74.0    male  29.0       0       0       0   
2  182-3.cha   NaN    male   NaN       0       0       0   
3  121-0.cha  70.0  female  30.0       0       1       0   
4  142-3.cha  61.0  female  30.0       0       0       0   

   count_unintelligible  count_trailing  count_repetitions category  \
0                     0               1                  3  Control   
1                     0               0                  0  Control   
2                     0               1                  0  Control   
3                     0               0                  0  Control   
4                     0               0                  0  Control   

                                                data  
0    there's a cookie jar on the shelf . and the ...  
1   the kids are in the cookies . the stool is fa...  
2   well Johnny's falling off the stool . the boy...  
3    the boy is taking a cookie outof the cookie ...  
4    well the water's running over on the floor ....

In [4]:
df_sub = df.loc[df.category.isin([ "Control", "ProbableAD"])] #read the important identity
df_sub

filepath   age  gender  mmse  pause1  pause2  pause3  \
0    138-1.cha  68.0  female  28.0       0       0       1   
1    631-0.cha  74.0    male  29.0       0       0       0   
2    182-3.cha   NaN    male   NaN       0       0       0   
3    121-0.cha  70.0  female  30.0       0       1       0   
4    142-3.cha  61.0  female  30.0       0       0       0   
5    086-2.cha   NaN  female   NaN       1       1       0   
6    267-2.cha  54.0  female  30.0       2       0       0   
7    118-4.cha   NaN  female   NaN       1       0       0   
8    166-2.cha   NaN    male   NaN       1       0       0   
9    105-1.cha  57.0  female  27.0       0       0       0   
10   021-4.cha   NaN  female   NaN       0       1       0   
11   105-0.cha  56.0  female  30.0       0       0       0   
12   140-0.cha  58.0  female  30.0       2       2       0   
13   298-1.cha  65.0    male  29.0       0       0       0   
14   086-3.cha   NaN  female   NaN       0       0       0   
15   107-2.cha   NaN    male   NaN       0       0       0   
16   121-1.cha  71.0  female  30.0       3       0       0   
17   059-4.cha   NaN  female   NaN       1       0       0   
18   243-0.cha  66.0    male  29.0       1       0       0   
19   142-0.cha  58.0  female  30.0       0       0       0   
20   121-3.cha  73.0  female  30.0       0       0       0   
21   086-1.cha  70.0  female  29.0       0       0       0   
22   105-2.cha   NaN  female   NaN       3       0       0   
23   166-1.cha  57.0    male  30.0       1       0       0   
24   042-4.cha   NaN  female   NaN       0       0       0   
25   166-0.cha  56.0    male  30.0       1       0       0   
26   140-3.cha  61.0  female  28.0       1       1       0   
27   267-0.cha  52.0  female  30.0       0       0       0   
28   086-0.cha  69.0  female  30.0       0       0       0   
29   121-2.cha  72.0  female  27.0       1       0       0   
..         ...   ...     ...   ...     ...     ...     ...   
515  213-1.cha  64.0    male  15.0       3       3       0   
516  235-2.cha   NaN    male   NaN       4       0       0   
517  270-2.cha  65.0  female  20.0       2       1       0   
518  466-1.cha  79.0  female  21.0       2       1       0   
519  091-2.cha  90.0  female  17.0       1       0       0   
520  029-0.cha  67.0    male  21.0       1       1       0   
523  091-0.cha  88.0  female  19.0       1       0       0   
524  213-3.cha   NaN    male   NaN       4       0       0   
525  270-0.cha  63.0  female  23.0       3       0       0   
526  235-0.cha  58.0    male  18.0       1       2       0   
527  349-1.cha  84.0  female  20.0       1       0       0   
528  010-4.cha   NaN    male   NaN       0       0       0   
529  134-0.cha  77.0  female  24.0       1       0       0   
532  350-0.cha  80.0  female  19.0       1       2       0   
533  168-1.cha  68.0  female  14.0       4       0       0   
534  269-1.cha  73.0  female  13.0       2       0       0   
535  051-0.cha  65.0  female  26.0       1       0       0   
536  544-1.cha  71.0    male  23.0       1       0       0   
537  544-0.cha  70.0    male  25.0       0       0       0   
538  051-1.cha  66.0  female  23.0       0       0       0   
539  269-0.cha  72.0  female  17.0       2       1       0   
540  168-0.cha  67.0  female  20.0       0       0       0   
541  350-1.cha  81.0  female  15.0       3       3       0   
544  349-0.cha  83.0  female  25.0       0       2       0   
545  134-1.cha  78.0  female  23.0       0       1       0   
546  157-2.cha   NaN    male   NaN       1       0       0   
547  270-1.cha  64.0  female  22.0       0       1       1   
548  213-2.cha   NaN    male   NaN       1       1       0   
549  091-1.cha  89.0  female  17.0       1       1       0   
551  029-1.cha  68.0    male  21.0       4       1       0   

     count_unintelligible  count_trailing  count_repetitions    category  \
0                       0               1                  3     Control   
1        

In [5]:
df_sub["data"].tolist() #collect all interview transcripts into a list

["  there's a cookie jar on the shelf . and the little boy's up on a stool . and the stool is about to fall he's about to fall . the stool's about to turn over . little girl in the picture's reaching for the cookie . mother is washing dishes . the water's running and running over onto the floor . she she has a plate in her hand and a towel . she's drying a plate . two cups are sitting on a counter and also a plate . you can see out through the kitchen window to another part of the house and a a walkway away from the house . you can see a window across in the other part of the house, the roof with a tree, that there are there are curtains on the windows .  I think that's did I cover it all ? yeah . ",
 " the kids are in the cookies . the stool is falling over . the mother's spilling the water and also drying the dishes . and the wind might be blowing the curtains . and the water's running . I can't tell is anything going on outside or not . I guess that's all I see . that's not very man

In [6]:
#data cleaning
REPLACE_NO_SPACE = re.compile("[.;:!\'?,\"()\[\]]") #delete all puntuations
REPLACE_WITH_SPACE = re.compile("(<br\s*/><br\s*/>)|(\-)|(\/)") #put space back in
NO_SPACE = ""
SPACE = " "

#data cleaning function
def preprocess_interviews(interviews):
    interviews = [REPLACE_NO_SPACE.sub("", line.lower()) for line in interviews]
    interviews = [REPLACE_WITH_SPACE.sub(" ", line) for line in interviews]
    
    return interviews #return processed data

interviews_train_clean = preprocess_interviews(df_sub["data"].tolist()) #put all cleaned data in a list

In [7]:
interviews_train_clean

['  theres a cookie jar on the shelf  and the little boys up on a stool  and the stool is about to fall hes about to fall  the stools about to turn over  little girl in the pictures reaching for the cookie  mother is washing dishes  the waters running and running over onto the floor  she she has a plate in her hand and a towel  shes drying a plate  two cups are sitting on a counter and also a plate  you can see out through the kitchen window to another part of the house and a a walkway away from the house  you can see a window across in the other part of the house the roof with a tree that there are there are curtains on the windows   i think thats did i cover it all  yeah  ',
 ' the kids are in the cookies  the stool is falling over  the mothers spilling the water and also drying the dishes  and the wind might be blowing the curtains  and the waters running  i cant tell is anything going on outside or not  i guess thats all i see  thats not very many  ',
 ' well johnnys falling off th

In [8]:
elmo_vectors = []

In [9]:
train_text = [[x] for x in interviews_train_clean]

In [10]:
train_text

[['  theres a cookie jar on the shelf  and the little boys up on a stool  and the stool is about to fall hes about to fall  the stools about to turn over  little girl in the pictures reaching for the cookie  mother is washing dishes  the waters running and running over onto the floor  she she has a plate in her hand and a towel  shes drying a plate  two cups are sitting on a counter and also a plate  you can see out through the kitchen window to another part of the house and a a walkway away from the house  you can see a window across in the other part of the house the roof with a tree that there are there are curtains on the windows   i think thats did i cover it all  yeah  '],
 [' the kids are in the cookies  the stool is falling over  the mothers spilling the water and also drying the dishes  and the wind might be blowing the curtains  and the waters running  i cant tell is anything going on outside or not  i guess thats all i see  thats not very many  '],
 [' well johnnys falling o

In [82]:
train_text_part = []
for i in range(400,477): #100 - 199 #左闭右开 #use 477 to include all 476 texts
    train_text_part.append(train_text[i])

In [83]:
train_text_part[76]

['  i see the little boy stealing cookies from the cookie jar  and the little girls he gave some to the little girl and shes eating some of the cookies  and i guess this is mama and shes washing the dishes  and she dropped a dish  no no she didnt drop a dish  the the water that shes washing the dishes with she let run  and its overflown overflown overflown  that doesnt that doesnt sound right  did it we forgot to turn off the spigot  and so the water is running off into the onto the floor here  and mom apparently is washing the dishes  and heres this little boy stealing the cookie cookies  hes gonna gonna fall because his the the cookies jar or the bench s the four legged stool whatever it is is is gonna fall over with him and the cookie jar  and mamas drying the dishes as usual for mamas if they dont have a husband that dries them or washes them or whatever  lets see now  i guess theres more things im sposta see  lets see here now  oh and the the water is flowing out of the of the sin

In [84]:
len(train_text_part)

77

In [85]:
#To make tf 2.0 compatible with tf1.0 code, we disable the tf2.0 functionalities
tf.disable_eager_execution()

In [86]:
elmo = hub.Module("https://tfhub.dev/google/elmo/2", trainable=True)

In [87]:
# just a random sentence

sentences = train_text_part



In [88]:
sentences

[[' oh my  you mean how much or just the ones   theres the sink is overflowing while shes wiping a plate and not looking  the little boy is hungry  he wants to get some cookies  and hes standing on a stool  and its tipping over  and i dont know whether hes gonna bring the cookie jar with him or what  and the little girl is holding up her hand wanting some  and hes gonna give to him  but i dont know if she has a finger to her mouth but and she knows that hes gonna be tipping over it looks like to me  or maybe shes just not noticing it and making her mouth get ready for this good cookie  i dont know which way it is for the little girl  because shes smiling  i think if she saw him falling over shed do something to to help him so he wouldnt get hurt  imean shed grab it or something  but shes just looking up at him youknow looking up at those good cookies and waiting for them to come to her hand  but this little finger in her mouth is im not quite sure what it means  i think it means that i

In [89]:
def get_elmo_vectors(x):
  embeddings = elmo(x, signature="default", as_dict=True)["elmo"]

  with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    sess.run(tf.tables_initializer())
    # return average of ELMo features
    return sess.run(tf.reduce_mean(embeddings,1))

In [90]:
# Extract ELMo embeddings
elmo_vectors_part = [get_elmo_vectors(x) for x in sentences]

INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


In [91]:
len(elmo_vectors_part)

77

In [92]:
elmo_vectors_part

[array([[-0.10673783, -0.14773004, -0.02326553, ...,  0.00377272,
          0.66122603,  0.06845764]], dtype=float32),
 array([[ 0.08682484, -0.03644485, -0.01204507, ...,  0.03307454,
          0.46138728,  0.04769931]], dtype=float32),
 array([[ 0.2013614 , -0.19664705,  0.00282143, ...,  0.07228779,
          0.38507906,  0.15444453]], dtype=float32),
 array([[-0.03976833, -0.08882086,  0.02817707, ..., -0.07872383,
          0.5610051 , -0.00468263]], dtype=float32),
 array([[-0.01358772, -0.11245718,  0.04418973, ..., -0.07018895,
          0.54916835,  0.04642474]], dtype=float32),
 array([[ 0.15392321, -0.17527819,  0.11936738, ...,  0.00409883,
          0.49386704, -0.03748539]], dtype=float32),
 array([[-0.11500037, -0.1626498 , -0.09898206, ...,  0.15219659,
          0.5476619 , -0.01862704]], dtype=float32),
 array([[-0.10729565,  0.06626553, -0.0543077 , ...,  0.07841564,
          0.4479375 ,  0.0481075 ]], dtype=float32),
 array([[-0.09508482, -0.0584964 , -0.01779963, 

In [93]:
elmo_vectors = elmo_vectors+elmo_vectors_part

In [94]:
len(elmo_vectors)

476

In [95]:
print("Shape of each sentence embedding:")
for x in elmo_vectors:
    print(x.shape)

Shape of each sentence embedding:
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 1024)
(1, 10

In [110]:
len(elmo_vectors)

476

In [111]:
elmo_vecs = []
for sublist in elmo_vectors:
    for item in sublist:
        elmo_vecs.append(item)

In [112]:
elmo_vecs

[array([ 0.25159258,  0.02076257, -0.00920534, ...,  0.07811424,
         0.5708164 ,  0.00484926], dtype=float32),
 array([ 0.2540095 , -0.14774652,  0.04500685, ...,  0.08484393,
         0.52722937, -0.00663076], dtype=float32),
 array([-0.0998107 , -0.03377883, -0.0558092 , ..., -0.004955  ,
         0.44657955,  0.16277756], dtype=float32),
 array([0.1579949 , 0.06644518, 0.0584579 , ..., 0.15729694, 0.5598118 ,
        0.03759524], dtype=float32),
 array([-0.08112554, -0.07984114, -0.0194974 , ..., -0.0285372 ,
         0.5952    ,  0.00599547], dtype=float32),
 array([ 0.00062499,  0.05985605, -0.07640619, ..., -0.00217756,
         0.5873181 , -0.11979379], dtype=float32),
 array([ 0.00806571, -0.13907361, -0.1223456 , ...,  0.23042507,
         0.49992394,  0.23734991], dtype=float32),
 array([-0.01413198,  0.07396255, -0.11735865, ..., -0.04683429,
         0.53032076,  0.06486255], dtype=float32),
 array([ 0.02811883,  0.03255862, -0.02039186, ...,  0.08681343,
         0.45

In [113]:
column_names = ["elmov"+str(i) for i in range(1024)]
column_names

['elmov0',
 'elmov1',
 'elmov2',
 'elmov3',
 'elmov4',
 'elmov5',
 'elmov6',
 'elmov7',
 'elmov8',
 'elmov9',
 'elmov10',
 'elmov11',
 'elmov12',
 'elmov13',
 'elmov14',
 'elmov15',
 'elmov16',
 'elmov17',
 'elmov18',
 'elmov19',
 'elmov20',
 'elmov21',
 'elmov22',
 'elmov23',
 'elmov24',
 'elmov25',
 'elmov26',
 'elmov27',
 'elmov28',
 'elmov29',
 'elmov30',
 'elmov31',
 'elmov32',
 'elmov33',
 'elmov34',
 'elmov35',
 'elmov36',
 'elmov37',
 'elmov38',
 'elmov39',
 'elmov40',
 'elmov41',
 'elmov42',
 'elmov43',
 'elmov44',
 'elmov45',
 'elmov46',
 'elmov47',
 'elmov48',
 'elmov49',
 'elmov50',
 'elmov51',
 'elmov52',
 'elmov53',
 'elmov54',
 'elmov55',
 'elmov56',
 'elmov57',
 'elmov58',
 'elmov59',
 'elmov60',
 'elmov61',
 'elmov62',
 'elmov63',
 'elmov64',
 'elmov65',
 'elmov66',
 'elmov67',
 'elmov68',
 'elmov69',
 'elmov70',
 'elmov71',
 'elmov72',
 'elmov73',
 'elmov74',
 'elmov75',
 'elmov76',
 'elmov77',
 'elmov78',
 'elmov79',
 'elmov80',
 'elmov81',
 'elmov82',
 'elmov83',
 '

In [114]:
len(column_names)

1024

In [115]:
elmovecs_df = pd.DataFrame(elmo_vecs)

In [ ]:
elmovecs_df.columns = column_names

In [118]:
elmovecs_df

elmov0    elmov1    elmov2    elmov3    elmov4    elmov5    elmov6  \
0    0.251593  0.020763 -0.009205  0.002106  0.136264  0.287263 -0.055806   
1    0.254009 -0.147747  0.045007  0.089490  0.177276  0.167827 -0.026437   
2   -0.099811 -0.033779 -0.055809 -0.012933  0.091413  0.082503 -0.057615   
3    0.157995  0.066445  0.058458  0.194358  0.020746  0.091865  0.079901   
4   -0.081126 -0.079841 -0.019497  0.037332  0.256142  0.153642 -0.001719   
5    0.000625  0.059856 -0.076406 -0.010028  0.146430  0.017271  0.051622   
6    0.008066 -0.139074 -0.122346  0.094338  0.005450  0.139544 -0.101851   
7   -0.014132  0.073963 -0.117359  0.017517  0.144658  0.095344 -0.102162   
8    0.028119  0.032559 -0.020392  0.023757  0.114377  0.037145  0.035356   
9   -0.037541 -0.032611 -0.024463 -0.087944  0.159127  0.005041  0.071873   
10  -0.093587 -0.081867  0.040303  0.003324  0.178280  0.174557  0.083422   
11   0.033642 -0.121149  0.064223 -0.074274  0.186805  0.240925 -0.106926   
12  -0.071155 -0.167017 -0.085744  0.030791  0.071265  0.135047 -0.024314   
13  -0.008728 -0.018436 -0.036486 -0.042081  0.250001  0.151461  0.020656   
14   0.151062  0.056935  0.049930  0.131104  0.147882  0.054889 -0.083407   
15   0.060562 -0.098113  0.085228 -0.030961  0.056246  0.041236  0.077427   
16  -0.016608 -0.046787 -0.180196 -0.080012  0.085278  0.103194 -0.030548   
17   0.007476 -0.058741 -0.034259 -0.109524  0.076367  0.064239 -0.074363   
18  -0.079495 -0.096309 -0.060115  0.033142  0.282801  0.062066  0.007402   
19  -0.062135 -0.077512 -0.030393  0.019896  0.099237  0.062768 -0.030770   
20   0.002319  0.059842 -0.027990  0.034990  0.094563  0.031386  0.016490   
21   0.070375 -0.180416  0.020798 -0.034304  0.162979  0.245742 -0.144791   
22  -0.062902 -0.097330 -0.047625 -0.076777  0.096887  0.079918 -0.032527   
23  -0.005553 -0.042476 -0.008396 -0.065713  0.249902  0.112099  0.033966   
24  -0.001570 -0.039236  0.101555 -0.075560  0.008601  0.090112  0.026283   
25   0.190969 -0.073523  0.051271  0.079834  0.269145  0.305012 -0.123537   
26  -0.131862  0.031602 -0.031930  0.033298  0.125936  0.045851  0.013953   
27  -0.060144 -0.148463 -0.008673 -0.034651  0.159136  0.219916 -0.129274   
28  -0.140816 -0.022645  0.003319 -0.009245  0.141981  0.082960  0.080090   
29  -0.018350 -0.117976 -0.015277  0.103801  0.112615  0.106174  0.015042   
..        ...       ...       ...       ...       ...       ...       ...   
446 -0.223009 -0.217822 -0.063533 -0.094700  0.233091  0.217828 -0.212116   
447  0.031506 -0.052270  0.002364 -0.075810  0.138050  0.141975 -0.144576   
448 -0.056607 -0.133663  0.002964 -0.159723  0.169865  0.005468  0.045861   
449  0.017633  0.093481 -0.046058  0.086954  0.083288 -0.026522  0.057703   
450  0.111243  0.024950 -0.221103  0.022856  0.087917  0.018436  0.022137   
451 -0.115522 -0.062760 -0.071432  0.013228  0.305205  0.144837 -0.065342   
452  0.054864  0.028833  0.017005  0.053781  0.113569  0.118401 -0.014709   
453 -0.007041 -0.239907  0.040067 -0.139779  0.145902  0.202524 -0.087218   
454 -0.045246 -0.071278 -0.209306 -0.134098  0.247655  0.109184 -0.089139   
455  0.000178 -0.196058 -0.083548  0.060298  0.262917  0.282885 -0.102496   
456  0.103027  0.012802  0.050821  0.060194  0.219240  0.145051  0.073103   
457  0.051196 -0.118771  0.099876  0.103195  0.248760  0.368226 -0.070418   
458 -0.078310 -0.071178  0.010025 -0.119678  0.140501  0.155594 -0.041355   
459  0.045678 -0.103869 -0.012673 -0.052387  0.248353  0.218859 -0.064007   
460 -0.127581 -0.264852 -0.010218 -0.103645  0.345146  0.267242 -0.075775   
461  0.194234 -0.182929  0.151254 -0.047798  0.314261  0.209364 -0.037771   
462  0.131694 -0.159488  0.024281  0.096957  0.140376  0.192000 -0.048538   
463  0.101840 -0.057789 -0.077777 -0.011628  0.198873  0.206503 -0.015382   
464  0.114077 -0.096178 -0.065598 -0.102280  0.018297  0.149055 -0.055159   
465  0.055037 -0.176411 -0.088311  0.071355  0.306174  0.293593 -0.165493   
466

In [119]:
elmovecs_df.to_csv('elmo_vectors.csv')

In [120]:
elmovecs_df = pd.read_csv("elmo_vectors.csv")
elmovecs_df

elmov0    elmov1    elmov2    elmov3    elmov4    elmov5    elmov6  \
0    0.251593  0.020763 -0.009205  0.002106  0.136264  0.287263 -0.055806   
1    0.254009 -0.147747  0.045007  0.089490  0.177276  0.167827 -0.026437   
2   -0.099811 -0.033779 -0.055809 -0.012933  0.091413  0.082503 -0.057615   
3    0.157995  0.066445  0.058458  0.194358  0.020746  0.091865  0.079901   
4   -0.081126 -0.079841 -0.019497  0.037332  0.256142  0.153642 -0.001719   
5    0.000625  0.059856 -0.076406 -0.010028  0.146430  0.017271  0.051622   
6    0.008066 -0.139074 -0.122346  0.094338  0.005450  0.139544 -0.101851   
7   -0.014132  0.073963 -0.117359  0.017517  0.144658  0.095344 -0.102162   
8    0.028119  0.032559 -0.020392  0.023757  0.114377  0.037145  0.035356   
9   -0.037541 -0.032611 -0.024463 -0.087944  0.159127  0.005041  0.071873   
10  -0.093587 -0.081867  0.040303  0.003324  0.178280  0.174557  0.083422   
11   0.033642 -0.121149  0.064223 -0.074274  0.186805  0.240925 -0.106926   
12  -0.071155 -0.167017 -0.085744  0.030791  0.071265  0.135047 -0.024314   
13  -0.008728 -0.018436 -0.036486 -0.042081  0.250001  0.151461  0.020656   
14   0.151062  0.056935  0.049930  0.131104  0.147882  0.054889 -0.083407   
15   0.060562 -0.098113  0.085228 -0.030961  0.056246  0.041236  0.077427   
16  -0.016608 -0.046787 -0.180196 -0.080012  0.085278  0.103194 -0.030548   
17   0.007476 -0.058741 -0.034259 -0.109524  0.076367  0.064239 -0.074363   
18  -0.079495 -0.096309 -0.060115  0.033142  0.282801  0.062066  0.007402   
19  -0.062135 -0.077512 -0.030393  0.019896  0.099237  0.062768 -0.030770   
20   0.002319  0.059842 -0.027990  0.034990  0.094563  0.031386  0.016490   
21   0.070375 -0.180416  0.020798 -0.034304  0.162979  0.245742 -0.144791   
22  -0.062902 -0.097330 -0.047625 -0.076777  0.096887  0.079918 -0.032527   
23  -0.005553 -0.042476 -0.008396 -0.065713  0.249902  0.112099  0.033966   
24  -0.001570 -0.039236  0.101555 -0.075560  0.008601  0.090112  0.026283   
25   0.190969 -0.073523  0.051271  0.079834  0.269145  0.305012 -0.123537   
26  -0.131862  0.031602 -0.031930  0.033298  0.125936  0.045851  0.013953   
27  -0.060144 -0.148463 -0.008673 -0.034651  0.159136  0.219916 -0.129274   
28  -0.140816 -0.022645  0.003319 -0.009245  0.141981  0.082960  0.080090   
29  -0.018350 -0.117976 -0.015277  0.103801  0.112615  0.106174  0.015042   
..        ...       ...       ...       ...       ...       ...       ...   
446 -0.223009 -0.217822 -0.063533 -0.094700  0.233091  0.217828 -0.212116   
447  0.031506 -0.052270  0.002364 -0.075810  0.138050  0.141975 -0.144576   
448 -0.056607 -0.133663  0.002964 -0.159723  0.169865  0.005468  0.045861   
449  0.017633  0.093481 -0.046058  0.086954  0.083288 -0.026522  0.057703   
450  0.111243  0.024950 -0.221103  0.022856  0.087917  0.018436  0.022137   
451 -0.115522 -0.062760 -0.071432  0.013228  0.305205  0.144837 -0.065342   
452  0.054864  0.028833  0.017005  0.053781  0.113569  0.118401 -0.014709   
453 -0.007041 -0.239907  0.040067 -0.139779  0.145902  0.202524 -0.087218   
454 -0.045246 -0.071278 -0.209306 -0.134098  0.247655  0.109184 -0.089139   
455  0.000178 -0.196058 -0.083548  0.060298  0.262917  0.282885 -0.102496   
456  0.103027  0.012802  0.050821  0.060194  0.219240  0.145051  0.073103   
457  0.051196 -0.118771  0.099876  0.103195  0.248760  0.368226 -0.070418   
458 -0.078310 -0.071178  0.010025 -0.119678  0.140501  0.155594 -0.041355   
459  0.045678 -0.103869 -0.012673 -0.052387  0.248353  0.218859 -0.064007   
460 -0.127581 -0.264852 -0.010218 -0.103645  0.345146  0.267242 -0.075775   
461  0.194234 -0.182929  0.151254 -0.047798  0.314261  0.209364 -0.037771   
462  0.131694 -0.159488  0.024281  0.096957  0.140376  0.192000 -0.048538   
463  0.101840 -0.057789 -0.077777 -0.011628  0.198873  0.206503 -0.015382   
464  0.114077 -0.096178 -0.065598 -0.102280  0.018297  0.149055 -0.055159   
465  0.055037 -0.176411 -0.088311  0.071355  0.306174  0.293593 -0.165493   
466

In [121]:
docvecs_df = pd.read_csv("doc2vec.csv")
docvecs_df

docvecs0  docvecs1  docvecs2  docvecs3  docvecs4  docvecs5  docvecs6  \
0   -0.151947 -0.371280 -0.316788  0.218896  0.075059  0.085084 -0.014939   
1    0.027595 -0.244941 -0.015700  0.170830  0.000994  0.092973 -0.060648   
2   -0.366985  0.126893 -0.169838  0.375112 -0.321718  0.236652  0.260350   
3    0.254116  0.496882 -0.460124  0.546128 -0.271839  0.488808  0.580052   
4   -0.267923  0.645562  0.122693 -0.173702  0.362269  0.026052  0.366241   
5    0.160577  0.424869 -0.110945  0.191033  0.265074  0.501161 -0.215904   
6   -0.211155  0.255086 -0.367761  0.909073  0.304671  0.381588  0.827917   
7    0.071684  0.350215 -0.244403 -0.640559 -0.466073 -0.465960  0.524605   
8    0.284128 -0.025980 -0.460626  0.184742  0.134648  0.430071  0.022102   
9    0.693649  0.273983 -0.567578  0.206454 -0.040428  0.373651  0.341942   
10   0.004569  0.129328 -0.311143  0.198135  0.226608  0.187916  0.341507   
11  -0.491059  0.286362  0.079408 -0.256438 -0.228089  0.354579  0.172693   
12  -0.298727  0.256485 -0.013876  0.034432 -0.071799  0.125317  0.575882   
13  -1.102882  0.455318  0.244802 -0.471483 -0.637604  0.152473  0.004163   
14   0.216217 -0.521388 -0.221598  0.076177  0.407744  0.346072 -0.332804   
15  -0.086203 -0.015608 -0.030569 -0.214417 -0.523037 -0.565509  0.023766   
16   0.506392  0.310490 -0.213816  0.312873  0.193914  0.149938  0.297474   
17  -0.412763  0.378632 -0.375939  0.274505 -0.313345 -0.055742 -0.190999   
18   0.549699  0.136855 -0.208542  0.658542 -0.050839  0.625627  0.529104   
19  -0.229160  0.322751 -0.334345  0.046534  0.287638  0.028662  0.267841   
20   0.373906  0.509848 -0.323240  0.047451 -0.259734  0.720449  0.082120   
21  -0.405174  0.057361 -0.241135  0.115464 -0.080244  0.504922 -0.015796   
22  -0.117478  0.111772  0.059072  0.165672 -0.432930 -0.565479  0.109042   
23  -0.044434 -0.271449 -0.051391 -0.371591 -0.663233 -0.180363  0.034618   
24   0.547264 -0.252869 -0.837991 -0.040447  0.306977  0.697076  0.214975   
25  -0.568441  0.230318  0.101442  0.576800  0.226531 -0.021593  0.433298   
26   0.278649  0.077170 -0.133278  0.125462  0.323147  0.395514  0.162267   
27   0.069373  0.064429 -0.138671  0.069336 -0.041701 -0.074750 -0.354946   
28   0.067788  0.498486 -0.427629 -0.371972 -0.158891  0.182113  0.295622   
29   0.071890  0.017785  0.337610 -0.085168 -0.311194 -0.742952  0.092497   
..        ...       ...       ...       ...       ...       ...       ...   
447 -0.045404  0.057033 -0.384155  0.467230 -0.141641 -0.233299  0.185996   
448  0.612692  0.051977  0.050789  0.812432  0.075641  0.489539  0.233072   
449  0.294605  0.012019  0.378268  0.040187  0.377363  0.488784  0.280744   
450 -0.342463  0.225675 -0.634655  0.014302 -0.399156  0.795014 -0.302930   
451  0.105071  0.423970 -0.678305 -1.185953 -0.387789  0.466384 -0.395201   
452  0.452278  0.363568  0.344044  0.009126  0.006262  0.610414  0.682213   
453  0.007454  0.201148  0.160398  0.170361 -0.180965  0.169401  0.512584   
454  0.170601  0.053712 -0.193687  0.247287 -0.524309  0.718553 -0.150281   
455  0.443057 -0.003556 -0.205321  0.584801 -0.343864  0.202919  0.304673   
456 -0.179911 -0.570701 -0.130319 -0.597754 -0.015882  0.200322 -0.045258   
457  0.012509 -0.086299  0.015934 -0.196058 -0.103688  0.173864  0.049159   
458 -0.341213  0.377104  0.075317 -0.454495 -0.135168  0.179813 -0.240127   
459 -0.415101  0.253549  0.145288 -0.048176 -0.264048 -0.298742 -0.211735   
460  0.012956  0.330995 -0.175373  0.089962  0.284261 -0.203762  0.087643   
461  0.029401 -0.160021 -0.286829 -0.238605 -0.187331  0.576577  0.022826   
462  0.521575  0.278750 -0.306982  0.092345  0.033865  0.269410  0.202027   
463 -0.346695  0.122641 -0.084322 -0.345569  0.004032  0.098742 -0.151399   
464  0.575319  0.292371 -0.206573 -0.578566 -0.259812  0.158381 -0.162168   
465 -0.635765 -0.252816  0.042961  0.367878  0.048372 -0.255691 -0.018894   
466 -0.514349 -0.561800  0.156088  0.585792 -0.086446 -0.370993 -0.160979   
4

In [122]:
#Count Vectorizer
cv = CountVectorizer(binary=True) 
cv.fit(interviews_train_clean) #fit the data
X = cv.transform(interviews_train_clean) 

In [123]:
df_sub["gender"] = df_sub["gender"].astype('category')
df_sub.dtypes
df_sub["gender"] = df_sub["gender"].cat.codes
df_sub.head()

filepath   age  gender  mmse  pause1  pause2  pause3  \
0  138-1.cha  68.0       0  28.0       0       0       1   
1  631-0.cha  74.0       1  29.0       0       0       0   
2  182-3.cha   NaN       1   NaN       0       0       0   
3  121-0.cha  70.0       0  30.0       0       1       0   
4  142-3.cha  61.0       0  30.0       0       0       0   

   count_unintelligible  count_trailing  count_repetitions category  \
0                     0               1                  3  Control   
1                     0               0                  0  Control   
2                     0               1                  0  Control   
3                     0               0                  0  Control   
4                     0               0                  0  Control   

                                                data  
0    there's a cookie jar on the shelf . and the ...  
1   the kids are in the cookies . the stool is fa...  
2   well Johnny's falling off the stool . the boy...  
3    the boy is taking a cookie outof the cookie ...  
4    well the water's running over on the floor ....

In [124]:
age_mean = df_sub["age"].mean()
df_sub

filepath   age  gender  mmse  pause1  pause2  pause3  \
0    138-1.cha  68.0       0  28.0       0       0       1   
1    631-0.cha  74.0       1  29.0       0       0       0   
2    182-3.cha   NaN       1   NaN       0       0       0   
3    121-0.cha  70.0       0  30.0       0       1       0   
4    142-3.cha  61.0       0  30.0       0       0       0   
5    086-2.cha   NaN       0   NaN       1       1       0   
6    267-2.cha  54.0       0  30.0       2       0       0   
7    118-4.cha   NaN       0   NaN       1       0       0   
8    166-2.cha   NaN       1   NaN       1       0       0   
9    105-1.cha  57.0       0  27.0       0       0       0   
10   021-4.cha   NaN       0   NaN       0       1       0   
11   105-0.cha  56.0       0  30.0       0       0       0   
12   140-0.cha  58.0       0  30.0       2       2       0   
13   298-1.cha  65.0       1  29.0       0       0       0   
14   086-3.cha   NaN       0   NaN       0       0       0   
15   107-2.cha   NaN       1   NaN       0       0       0   
16   121-1.cha  71.0       0  30.0       3       0       0   
17   059-4.cha   NaN       0   NaN       1       0       0   
18   243-0.cha  66.0       1  29.0       1       0       0   
19   142-0.cha  58.0       0  30.0       0       0       0   
20   121-3.cha  73.0       0  30.0       0       0       0   
21   086-1.cha  70.0       0  29.0       0       0       0   
22   105-2.cha   NaN       0   NaN       3       0       0   
23   166-1.cha  57.0       1  30.0       1       0       0   
24   042-4.cha   NaN       0   NaN       0       0       0   
25   166-0.cha  56.0       1  30.0       1       0       0   
26   140-3.cha  61.0       0  28.0       1       1       0   
27   267-0.cha  52.0       0  30.0       0       0       0   
28   086-0.cha  69.0       0  30.0       0       0       0   
29   121-2.cha  72.0       0  27.0       1       0       0   
..         ...   ...     ...   ...     ...     ...     ...   
515  213-1.cha  64.0       1  15.0       3       3       0   
516  235-2.cha   NaN       1   NaN       4       0       0   
517  270-2.cha  65.0       0  20.0       2       1       0   
518  466-1.cha  79.0       0  21.0       2       1       0   
519  091-2.cha  90.0       0  17.0       1       0       0   
520  029-0.cha  67.0       1  21.0       1       1       0   
523  091-0.cha  88.0       0  19.0       1       0       0   
524  213-3.cha   NaN       1   NaN       4       0       0   
525  270-0.cha  63.0       0  23.0       3       0       0   
526  235-0.cha  58.0       1  18.0       1       2       0   
527  349-1.cha  84.0       0  20.0       1       0       0   
528  010-4.cha   NaN       1   NaN       0       0       0   
529  134-0.cha  77.0       0  24.0       1       0       0   
532  350-0.cha  80.0       0  19.0       1       2       0   
533  168-1.cha  68.0       0  14.0       4       0       0   
534  269-1.cha  73.0       0  13.0       2       0       0   
535  051-0.cha  65.0       0  26.0       1       0       0   
536  544-1.cha  71.0       1  23.0       1       0       0   
537  544-0.cha  70.0       1  25.0       0       0       0   
538  051-1.cha  66.0       0  23.0       0       0       0   
539  269-0.cha  72.0       0  17.0       2       1       0   
540  168-0.cha  67.0       0  20.0       0       0       0   
541  350-1.cha  81.0       0  15.0       3       3       0   
544  349-0.cha  83.0       0  25.0       0       2       0   
545  134-1.cha  78.0       0  23.0       0       1       0   
546  157-2.cha   NaN       1   NaN       1       0       0   
547  270-1.cha  64.0       0  22.0       0       1       1   
548  213-2.cha   NaN       1   NaN       1       1       0   
549  091-1.cha  89.0       0  17.0       1       1       0   
551  029-1.cha  68.0       1  21.0       4       1       0   

     count_unintelligible  count_trailing  count_repetitions    category  \
0                       0               1                  3     Control   
1        

In [125]:
df_sub[df_sub.isnull().any(axis=1)].shape

(82, 12)

In [126]:
df_sub.fillna({"age": age_mean}, inplace=True)

In [127]:
df_sub

filepath        age  gender  mmse  pause1  pause2  pause3  \
0    138-1.cha  68.000000       0  28.0       0       0       1   
1    631-0.cha  74.000000       1  29.0       0       0       0   
2    182-3.cha  68.155779       1   NaN       0       0       0   
3    121-0.cha  70.000000       0  30.0       0       1       0   
4    142-3.cha  61.000000       0  30.0       0       0       0   
5    086-2.cha  68.155779       0   NaN       1       1       0   
6    267-2.cha  54.000000       0  30.0       2       0       0   
7    118-4.cha  68.155779       0   NaN       1       0       0   
8    166-2.cha  68.155779       1   NaN       1       0       0   
9    105-1.cha  57.000000       0  27.0       0       0       0   
10   021-4.cha  68.155779       0   NaN       0       1       0   
11   105-0.cha  56.000000       0  30.0       0       0       0   
12   140-0.cha  58.000000       0  30.0       2       2       0   
13   298-1.cha  65.000000       1  29.0       0       0       0   
14   086-3.cha  68.155779       0   NaN       0       0       0   
15   107-2.cha  68.155779       1   NaN       0       0       0   
16   121-1.cha  71.000000       0  30.0       3       0       0   
17   059-4.cha  68.155779       0   NaN       1       0       0   
18   243-0.cha  66.000000       1  29.0       1       0       0   
19   142-0.cha  58.000000       0  30.0       0       0       0   
20   121-3.cha  73.000000       0  30.0       0       0       0   
21   086-1.cha  70.000000       0  29.0       0       0       0   
22   105-2.cha  68.155779       0   NaN       3       0       0   
23   166-1.cha  57.000000       1  30.0       1       0       0   
24   042-4.cha  68.155779       0   NaN       0       0       0   
25   166-0.cha  56.000000       1  30.0       1       0       0   
26   140-3.cha  61.000000       0  28.0       1       1       0   
27   267-0.cha  52.000000       0  30.0       0       0       0   
28   086-0.cha  69.000000       0  30.0       0       0       0   
29   121-2.cha  72.000000       0  27.0       1       0       0   
..         ...        ...     ...   ...     ...     ...     ...   
515  213-1.cha  64.000000       1  15.0       3       3       0   
516  235-2.cha  68.155779       1   NaN       4       0       0   
517  270-2.cha  65.000000       0  20.0       2       1       0   
518  466-1.cha  79.000000       0  21.0       2       1       0   
519  091-2.cha  90.000000       0  17.0       1       0       0   
520  029-0.cha  67.000000       1  21.0       1       1       0   
523  091-0.cha  88.000000       0  19.0       1       0       0   
524  213-3.cha  68.155779       1   NaN       4       0       0   
525  270-0.cha  63.000000       0  23.0       3       0       0   
526  235-0.cha  58.000000       1  18.0       1       2       0   
527  349-1.cha  84.000000       0  20.0       1       0       0   
528  010-4.cha  68.155779       1   NaN       0       0       0   
529  134-0.cha  77.000000       0  24.0       1       0       0   
532  350-0.cha  80.000000       0  19.0       1       2       0   
533  168-1.cha  68.000000       0  14.0       4       0       0   
534  269-1.cha  73.000000       0  13.0       2       0       0   
535  051-0.cha  65.000000       0  26.0       1       0       0   
536  544-1.cha  71.000000       1  23.0       1       0       0   
537  544-0.cha  70.000000       1  25.0       0       0       0   
538  051-1.cha  66.000000       0  23.0       0       0       0   
539  269-0.cha  72.000000       0  17.0       2       1       0   
540  168-0.cha  67.000000       0  20.0       0       0       0   
541  350-1.cha  81.000000       0  15.0       3       3       0   
544  349-0.cha  83.000000       0  25.0       0       2       0   
545  134-1.cha  78.000000       0  23.0       0       1       0   
546  157-2.cha  68.155779       1   NaN       1       0       0   
547  270-1.cha  64.000000       0  22.0       0       1       1   
548  213-2.cha  68.155779       1   NaN       1      

In [128]:
X_df = pd.DataFrame(X.todense())
df_sub = df_sub[["age","gender","pause1", "pause2", "pause3", "count_unintelligible", "count_trailing", "count_repetitions", "category"]]
df_sub.reset_index(drop=True, inplace=True)
X = df_sub.join(X_df)

In [129]:
X

age  gender  pause1  pause2  pause3  count_unintelligible  \
0    68.000000       0       0       0       1                     0   
1    74.000000       1       0       0       0                     0   
2    68.155779       1       0       0       0                     0   
3    70.000000       0       0       1       0                     0   
4    61.000000       0       0       0       0                     0   
5    68.155779       0       1       1       0                     0   
6    54.000000       0       2       0       0                     0   
7    68.155779       0       1       0       0                     0   
8    68.155779       1       1       0       0                     0   
9    57.000000       0       0       0       0                     0   
10   68.155779       0       0       1       0                     0   
11   56.000000       0       0       0       0                     1   
12   58.000000       0       2       2       0                     0   
13   65.000000       1       0       0       0                     0   
14   68.155779       0       0       0       0                     0   
15   68.155779       1       0       0       0                     0   
16   71.000000       0       3       0       0                     4   
17   68.155779       0       1       0       0                     0   
18   66.000000       1       1       0       0                     0   
19   58.000000       0       0       0       0                     0   
20   73.000000       0       0       0       0                     0   
21   70.000000       0       0       0       0                     2   
22   68.155779       0       3       0       0                     2   
23   57.000000       1       1       0       0                     0   
24   68.155779       0       0       0       0                     0   
25   56.000000       1       1       0       0                     0   
26   61.000000       0       1       1       0                     0   
27   52.000000       0       0       0       0                     0   
28   69.000000       0       0       0       0                     4   
29   72.000000       0       1       0       0                     0   
..         ...     ...     ...     ...     ...                   ...   
447  64.000000       1       3       3       0                     1   
448  68.155779       1       4       0       0                     0   
449  65.000000       0       2       1       0                     0   
450  79.000000       0       2       1       0                     0   
451  90.000000       0       1       0       0                     0   
452  67.000000       1       1       1       0                     0   
453  88.000000       0       1       0       0                     0   
454  68.155779       1       4       0       0                     0   
455  63.000000       0       3       0       0                     0   
456  58.000000       1       1       2       0                     1   
457  84.000000       0       1       0       0                     0   
458  68.155779       1       0       0       0                     2   
459  77.000000       0       1       0       0                     1   
460  80.000000       0       1       2       0                     0   
461  68.000000       0       4       0       0                     0   
462  73.000000       0       2       0       0                     0   
463  65.000000       0       1       0       0                     0   
464  71.000000       1       1       0       0                     0   
465  70.000000       1       0       0       0                     0   
466  66.000000       0       0       0       0                     1   
467  72.000000       0       2       1       0                     0   
468  67.000000       0       0       0       0                     0   
469  81.000000       0       3       3       0                     1   
470  83.000000       0       0       2       0     

In [130]:
X = elmovecs_df.join(X)

In [131]:
X = docvecs_df.join(X)

In [132]:
X

docvecs0  docvecs1  docvecs2  docvecs3  docvecs4  docvecs5  docvecs6  \
0   -0.151947 -0.371280 -0.316788  0.218896  0.075059  0.085084 -0.014939   
1    0.027595 -0.244941 -0.015700  0.170830  0.000994  0.092973 -0.060648   
2   -0.366985  0.126893 -0.169838  0.375112 -0.321718  0.236652  0.260350   
3    0.254116  0.496882 -0.460124  0.546128 -0.271839  0.488808  0.580052   
4   -0.267923  0.645562  0.122693 -0.173702  0.362269  0.026052  0.366241   
5    0.160577  0.424869 -0.110945  0.191033  0.265074  0.501161 -0.215904   
6   -0.211155  0.255086 -0.367761  0.909073  0.304671  0.381588  0.827917   
7    0.071684  0.350215 -0.244403 -0.640559 -0.466073 -0.465960  0.524605   
8    0.284128 -0.025980 -0.460626  0.184742  0.134648  0.430071  0.022102   
9    0.693649  0.273983 -0.567578  0.206454 -0.040428  0.373651  0.341942   
10   0.004569  0.129328 -0.311143  0.198135  0.226608  0.187916  0.341507   
11  -0.491059  0.286362  0.079408 -0.256438 -0.228089  0.354579  0.172693   
12  -0.298727  0.256485 -0.013876  0.034432 -0.071799  0.125317  0.575882   
13  -1.102882  0.455318  0.244802 -0.471483 -0.637604  0.152473  0.004163   
14   0.216217 -0.521388 -0.221598  0.076177  0.407744  0.346072 -0.332804   
15  -0.086203 -0.015608 -0.030569 -0.214417 -0.523037 -0.565509  0.023766   
16   0.506392  0.310490 -0.213816  0.312873  0.193914  0.149938  0.297474   
17  -0.412763  0.378632 -0.375939  0.274505 -0.313345 -0.055742 -0.190999   
18   0.549699  0.136855 -0.208542  0.658542 -0.050839  0.625627  0.529104   
19  -0.229160  0.322751 -0.334345  0.046534  0.287638  0.028662  0.267841   
20   0.373906  0.509848 -0.323240  0.047451 -0.259734  0.720449  0.082120   
21  -0.405174  0.057361 -0.241135  0.115464 -0.080244  0.504922 -0.015796   
22  -0.117478  0.111772  0.059072  0.165672 -0.432930 -0.565479  0.109042   
23  -0.044434 -0.271449 -0.051391 -0.371591 -0.663233 -0.180363  0.034618   
24   0.547264 -0.252869 -0.837991 -0.040447  0.306977  0.697076  0.214975   
25  -0.568441  0.230318  0.101442  0.576800  0.226531 -0.021593  0.433298   
26   0.278649  0.077170 -0.133278  0.125462  0.323147  0.395514  0.162267   
27   0.069373  0.064429 -0.138671  0.069336 -0.041701 -0.074750 -0.354946   
28   0.067788  0.498486 -0.427629 -0.371972 -0.158891  0.182113  0.295622   
29   0.071890  0.017785  0.337610 -0.085168 -0.311194 -0.742952  0.092497   
..        ...       ...       ...       ...       ...       ...       ...   
447 -0.045404  0.057033 -0.384155  0.467230 -0.141641 -0.233299  0.185996   
448  0.612692  0.051977  0.050789  0.812432  0.075641  0.489539  0.233072   
449  0.294605  0.012019  0.378268  0.040187  0.377363  0.488784  0.280744   
450 -0.342463  0.225675 -0.634655  0.014302 -0.399156  0.795014 -0.302930   
451  0.105071  0.423970 -0.678305 -1.185953 -0.387789  0.466384 -0.395201   
452  0.452278  0.363568  0.344044  0.009126  0.006262  0.610414  0.682213   
453  0.007454  0.201148  0.160398  0.170361 -0.180965  0.169401  0.512584   
454  0.170601  0.053712 -0.193687  0.247287 -0.524309  0.718553 -0.150281   
455  0.443057 -0.003556 -0.205321  0.584801 -0.343864  0.202919  0.304673   
456 -0.179911 -0.570701 -0.130319 -0.597754 -0.015882  0.200322 -0.045258   
457  0.012509 -0.086299  0.015934 -0.196058 -0.103688  0.173864  0.049159   
458 -0.341213  0.377104  0.075317 -0.454495 -0.135168  0.179813 -0.240127   
459 -0.415101  0.253549  0.145288 -0.048176 -0.264048 -0.298742 -0.211735   
460  0.012956  0.330995 -0.175373  0.089962  0.284261 -0.203762  0.087643   
461  0.029401 -0.160021 -0.286829 -0.238605 -0.187331  0.576577  0.022826   
462  0.521575  0.278750 -0.306982  0.092345  0.033865  0.269410  0.202027   
463 -0.346695  0.122641 -0.084322 -0.345569  0.004032  0.098742 -0.151399   
464  0.575319  0.292371 -0.206573 -0.578566 -0.259812  0.158381 -0.162168   
465 -0.635765 -0.252816  0.042961  0.367878  0.048372 -0.255691 -0.018894   
466 -0.514349 -0.561800  0.156088  0.585792 -0.086446 -0.370993 -0.160979   
4

In [133]:
y_list = df_sub['category'] #make a list of categories
y_list.shape

(477,)

In [134]:
#train test split and its function with the parameter # of times you want to see the validation accuracy
#also prints out maximum accuracy and its corresponding c each term, mean, and standard deviation
target = [1 if i == 'ProbableAD' else 0 for i in y_list] #这里要写啥
def run_classification_model(num_of_runs, X, target): #the function returns a list of test accuracy
    test_accuracy = [] #the list of accuracy should be empty before each time the function runs
    auc_list = []
    plt.figure(dpi = 800)
    for i in range(num_of_runs): #for loop that runs exact number of times requested
        print("run " + str(i)) #print out which run it is
        validation_accuracy = [] #the list of validation accuracy, the max will be drawn from it at the end
        X_train, X_test, y_train, y_test = train_test_split( #get a test set of 10% of the data, and a train set of 90%
            X, target, test_size = 0.1
        )

        X_train, X_val, y_train, y_val = train_test_split( #get a train set of 80%, and a validation set of 10%
            X_train, y_train, train_size = 0.89
        )
        
        c_list = [0.099, 0.01, 0.05, 0.25, 0.5, 1, 10, 100, 1000, 1e10] #list of hyperparameters
        for c in c_list: #test each c

            lr = LogisticRegression(C=c) #imput the c
            lr.fit(X_train, y_train) #fitting
            
            
            current_validation_accuracy = accuracy_score(y_val, lr.predict(X_val)) #calculate validation accuracy
            validation_accuracy.append(current_validation_accuracy) #append the list
            
        max_accuracy = max(validation_accuracy) #draw the maximum of validation accuracy
        index = np.argmax(validation_accuracy) #take the index of the maximum
        c_optim = c_list[index] #take the corresponding c
        print ("max validation accuracy is {} and optimal c is {}".format(max_accuracy, c_optim)) #print out the results
 
        # apply the best c to train the model
        lr_optim = LogisticRegression(C=c_optim) #try the best c on test set
        lr_optim.fit(X_train, y_train) #fitting
        current_test_accuracy = accuracy_score(y_test, lr_optim.predict(X_test)) #calculate test accuracy
        test_accuracy.append(current_test_accuracy) #append test accuracy list
        
        #plot AUC
        y_pred_proba = lr_optim.predict_proba(X_test)[::,1]
        fpr, tpr, _ = metrics.roc_curve(y_test, y_pred_proba)
        auc = metrics.roc_auc_score(y_test, y_pred_proba)
        auc_list.append(auc)
        plt.plot(fpr,tpr,label="ROC curve, AUC="+str(auc))   

    plt.xlabel('False Positive Rate')
    plt.ylabel('True Positive Rate')
    plt.title('Area Under the Curve for AD and healthy control classification')
    plt.legend(loc=4)
    plt.savefig("elmo_roc.png", dpi = 800)
    plt.show()
    
    return test_accuracy, auc_list #return the list

test_accuracy, auc_list = run_classification_model(1000, X.drop("category", axis=1), target) #call the function
mean_accuracy = np.mean(test_accuracy) #take the mean of test accuracy
std_accuracy = np.std(test_accuracy) #take standard deviation
print("Test Accuracy:",test_accuracy)
print("Test Accuracy Mean:",mean_accuracy)
print("Test Accuracy Std:",std_accuracy)

run 0


ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

<Figure size 4800x3200 with 0 Axes>

In [29]:
print(np.mean(auc_list))
print(np.std(auc_list))

0.9653172840401747
0.02170583556942998
